//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{
	internal class ServiceModel
	{
		public class ClientBase<T>
		{
			private string endpointConfigurationName;

			public ClientBase(string endpointConfigurationName)
			{
				this.endpointConfigurationName = endpointConfigurationName;
			}

			public object Channel { get; internal set; }
		}

		public class Channels
		{
		}

		internal class OperationContractAttribute : Attribute
		{
			public string ReplyAction { get; set; }
		}

		internal class ServiceContractAttribute : Attribute
		{
		}
	}
}